### PR TITLE
Mergenewresources

### PR DESCRIPTION
**Pull request by MarkieMark**
Hi Myung / Jaya / Ismael,

The pull request should contain all the modifications we made to the code base to add the most in-demand new FHIR Resource types;

We added proper build instructions too, as well as adjusting the maven directives so that it builds automatically from a top-level "mvn clean install" command

As you'll notice the code changes are quite incomplete; mainly although the new Resource types would appear as Resources on the server, most of the fields of the new Resources aren't fully coded. As Professor Braunstein has said we'll be accessing the MiHIN FHIR server for our projects this semester, the chances are we won't necessarily write all the details of that code for the time being; therefore it seems worthwhile making a timely pull request so that the changes are mergeable into the main codebase while they're fresh

The modified server code [without the more recent changes to master of https://github.com/i3l/GT-FHIR] is working at http://104.197.124.155/gt-fhir-webapp/ for the time being, although that's a time-limited free google cloud instance

Looking forward to hearing from you

Best regards

Mark

### CODE REVIEW

**Comment by ghost** [comment]
Mark,

So what you're saying is you would like us to do a pull and integrate these changes with our existing local repositories?

Thanks,
Jaya

**Comment by MarkieMark** [comment]
Hi Jaya,

As long as you're happy to, then I'd say it's worthwhile. The current state of mergenewresources includes the most recent changes to https://github.com/i3l/GT-FHIR master, so it should all be very workable

Best regards

Mark

**Comment by myungchoi** [comment]
Jaya,

Before integrating the pull request(s), please make sure you let me and Ismael know. We all need to know what has been changed and what impact it would have. 

All,
By the way, we are using OMOP database, which may not have all the necessary tables to hold the new resources we are trying to add. In this case, we may need to create a new table to hold the dataset. Please do this if you had to create a new table, use put “f_” front of all new tables.

And, please note that the Allergy related table will be deleted in our next upgrade. We are trying to find out a way to put the allergies in OMOP format. Then, the allergy related tables will be deleted. 

Thank you all for working on the FHIR server. 

Thanks,
Myung

**Comment by MarkieMark** [comment]
Hi Myung,

We were working with an empty [no data] database during development, we found that the app created the necessary tables when launched; although with no data, it was trivial to drop tables before launching a revised version of the app. There was no need to create tables manually. For the production server, I think an sqldump of the current data, without the data definition commands, would work, to recreate the current data when the database upgrades itself; I guess you do that [retrieving the data from an sqldump] already whenever you refresh the content of the database to its basis state? When you say OMOP database, I think that is the MySQL fhir_omop database that we found coded for

The changes to the code itself should all be visible at the most recent commit in that list, https://github.com/i3l/GT-FHIR/pull/91/commits/891e996becfe6032ba41afea487d8d93ec9ea054, basically we just added FHIR Resource types, without coding all the fields for those Resource types; though it would of course be optimal to code all the fields, there's a substantial chunk of work there already that is worth adding to the codebase even though there's more to do to perfect even the few Resource types we've added.

Then the very limited structural changes should be visible at https://github.com/i3l/GT-FHIR/pull/91/files; the build instructions are included as additions to the readme; while the maven changes were in the event virtually entirely simply to add suitable parent parameters so that a top-level clean install would invoke the submodules in the right order

Best regards

Mark

**Comment by myungchoi** [comment]
Mark,

Your pull request will be integrated. We need Isamel to take a look at the changes. I want to have “Go” from ismael as he is also working on the server code. He is in Brazil now. So, we need to give him a few days until he catch up with emails.

Thank you very much.

Jaya, please also look at the requests and see if they all look OK. I will also do that. If you have “Go” from Ismael and me, you can go ahead and integrate them.

Thanks.
Myung

**Comment by MarkieMark** [comment]
Hi Myung,

Thanks very much :-)

I should try to describe, in view of what you say re the database structure, how we added new FHIR Resource types, as I could adjust the naming of classes / tables to create a better distinction between OMOP & Non-OMOP Entities in edu.gatech.i3l.fhir.dstu2.entities at  gt-fhir-entities/src/main/java/edu/gatech/i3l/fhir/dstu2/entities/;

Basically we accorded with the current structure of an Entity being the primary class, mapping on the one hand to a database table, then mapping to a FHIR Resource with the getRelatedResource() / constructEntityFromResource() methods; as the schema of the OMOP Entities is that generally an OMOP Entity name is not identical to the FHIR Resource name, we just coded similar-yet-relatively-obvious Entity names as the Entity class names; Alert/Flag, Engagement/Appointment, EngagementResponse/AppointmentResponse, Individual/Person, Inoculation/Immunization, InoculationRecommendation/ImmunizationRecommendation, Message/Communication, MessageRequest/CommunicationRequest, ProcRequest/ProcedureRequest, Prognosis/RiskAssessment, Questions/Questionnaire, QuestionsAnswers/QuestionnaireResponse, ReferenceRequest/ReferralRequest, RelatedIndividual/RelatedPerson;

Thinking of what you said, that the f_ prefix would be helpful to distinguish OMOP tables from non-OMOP tables, my current thinking is that unless you say not to, then I'll be refactoring those class names before the merge, so that Alert is renamed as FHIRFlag, Engagement is renamed as FHIRAppointment, EngagementResponse is renamed as FHIRAppointmentResponse, Individual is renamed as FHIRPerson, Inoculation is renamed as FHIRImmunization, InoculationRecommendation is renamed as FHIRImmunizationRecommendation, Message is renamed as FHIRCommunication, MessageRequest is renamed as FHIRCommunicationRequest, ProcRequest is renamed as FHIRProcedureRequest, Prognosis is renamed as FHIRRiskAssessment, Questions is renamed as FHIRQuestionnaire, QuestionsAnswers is renamed as FHIRQuestionnaireResponse, ReferenceRequest is renamed as FHIRReferralRequest, RelatedIndividual is renamed as FHIRRelatedPerson, with the tables correspondingly renamed as f_flag, f_appointment, etcetera

Best regards

Mark

**Comment by ismael-sarmento-jr** [comment]
Good afternoon. As I am working on adjusting hapi-fihr (JPA project) to our
needs, so we won´t be behind their new features for data access layer, you
guys can commit to tech-on-fhir repo with no problems.

On Fri, Mar 18, 2016 at 2:13 PM, Myung Choi notifications@github.com
wrote:

> Mark,
> 
> Your pull request will be integrated. We need Isamel to take a look at the
> changes. I want to have “Go” from ismael as he is also working on the
> server code. He is in Brazil now. So, we need to give him a few days until
> he catch up with emails.
> 
> Thank you very much.
> 
> Jaya, please also look at the requests and see if they all look OK. I will
> also do that. If you have “Go” from Ismael and me, you can go ahead and
> integrate them.
> 
> Thanks.
> Myung
> 
> > On Mar 18, 2016, at 11:04 AM, Mark Benjamin notifications@github.com
> > wrote:
> > 
> > Hi Jaya,
> > 
> > As long as you're happy to, then I'd say it's worthwhile. The current
> > state of mergenewresources includes the most recent changes to
> > https://github.com/i3l/GT-FHIR https://github.com/i3l/GT-FHIR master,
> > so it should all be very workable
> > 
> > Best regards
> > 
> > Mark
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub <
> > https://github.com/i3l/GT-FHIR/pull/91#issuecomment-198400154>
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/i3l/GT-FHIR/pull/91#issuecomment-198458485

## 
-                 Ismael Sarmento de AC Junior*
                             Computer Programmer
                              GitHub
  https://github.com/ismael-sarmento-jr  LinkedIn
  http://br.linkedin.com/pub/ismael-sarmento/43/724/159/en

**Comment by i3lgatech** [comment]
DSTU version for this is changed. And, this issue has been resolved when upgrading to new DSTU.

**Pull request closed without merging**
